# Gvar 2c0daf9b-fc9e-47ee-bd7b-9850ac961d6f
<drac2>
stats = {
    "Dice Set":               	{"is_tool": True, "mod":charismaMod, "message":"is throwing dice"},
    "Playing Card Set":       	{"is_tool": True, "mod":charismaMod, "message":"is playing cards"},
    "Bagpipes":               	{"is_tool": True, "mod":charismaMod, "message":"is playing the bagpipes"},
    "Drum":                   	{"is_tool": True, "mod":charismaMod, "message":"is playing the drums"},
    "Dulcimer":               	{"is_tool": True, "mod":charismaMod, "message":"is playing a dulcimer"},
    "Lute":                   	{"is_tool": True, "mod":charismaMod, "message":"is playing a lute"},
    "Flute":                  	{"is_tool": True, "mod":charismaMod, "message":"is playing the flute"},
    "Lyre":                   	{"is_tool": True, "mod":charismaMod, "message":"is playing the lyre"},
    "Horn":                   	{"is_tool": True, "mod":charismaMod, "message":"is playing a horn"},
    "Pan Flute":              	{"is_tool": True, "mod":charismaMod, "message":"is playing a pan flute"},
    "Shawm":                  	{"is_tool": True, "mod":charismaMod, "message":"is playing the shawm"},
    "Viol":                   	{"is_tool": True, "mod":charismaMod, "message":"is playing the viol"},
    "Cobbler's Tools":        	{"is_tool": True, "mod":dexterityMod, "message":"is cobbling"},
    "Disguise Kit":           	{"is_tool": True, "mod":dexterityMod, "message":"has disguised themselves"},
    "Glassblower's Tools":    	{"is_tool": True, "mod":dexterityMod, "message":"is glassblowing"},
    "Jeweler's Tools":        	{"is_tool": True, "mod":dexterityMod, "message":"is working on jewelery"},
    "Potter's Tools":         	{"is_tool": True, "mod":dexterityMod, "message":"is working on pottery"},
    "Tinker's Tools":         	{"is_tool": True, "mod":dexterityMod, "message":"is tinkering"},
    "Thieves' Tools":         	{"is_tool": True, "mod":dexterityMod, "message":"is using Thieves' tools"},
    "Weaver's Tools":         	{"is_tool": True, "mod":dexterityMod, "message":"is weaving"},
    "Woodcarver's Tools":     	{"is_tool": True, "mod":dexterityMod, "message":"is carving"},
    "Alchemist's Supplies":   	{"is_tool": True, "mod":intelligenceMod, "message":"is doing alchemy"},
    "Calligrapher's Supplies":	{"is_tool": True, "mod":intelligenceMod, "message":"is doing calligraphy"},
    "Cartographer's Tools":   	{"is_tool": True, "mod":intelligenceMod, "message":"is doing cartography"},
    "Poisoner's Kit":         	{"is_tool": True, "mod":intelligenceMod, "message":"is working with poisons"},
    "Carpenter's Tools":      	{"is_tool": True, "mod":strengthMod, "message":"is doing carpentry"},
    "Leatherworker's Tools":  	{"is_tool": True, "mod":strengthMod, "message":"is doing leatherwork"}, 
    "Mason's Tools":          	{"is_tool": True, "mod":strengthMod, "message":"is doing masonary"}, 
    "Smith's Tools":          	{"is_tool": True, "mod":strengthMod, "message":"is smithing"},  
    "Brewer's Supplies":      	{"is_tool": True, "mod":wisdomMod, "message":"is brewing"}, 
    "Cook's Utensils":        	{"is_tool": True, "mod":wisdomMod, "message":"is cooking"}, 
    "Herbalism Kit":          	{"is_tool": True, "mod":wisdomMod, "message":"is working with herbs"},
    "Painter's Supplies":     	{"is_tool": True, "mod":wisdomMod, "message":"is painting"},
    "Navigator's Tools":      	{"is_tool": True, "mod":wisdomMod, "message":"is navigating"},
    "Performance":            	{"is_tool": False, "mod":character().skills.performance.value, "message":"is performing"},
    "History":                	{"is_tool": False, "mod":character().skills.history.value, "message":"uses historic knowledge"},
    "Persuasion":             	{"is_tool": False, "mod":character().skills.persuasion.value, "message":"is being persuasive"},
    "Arcana":                 	{"is_tool": False, "mod":character().skills.arcana.value, "message":"uses arcane knowledge"},
    "Athletics":              	{"is_tool": False, "mod":character().skills.athletics.value, "message":"is being athletic"},
    "Investigation":          	{"is_tool": False, "mod":character().skills.investigation.value, "message":"is investigating"},
    "Acrobatics":             	{"is_tool": False, "mod":character().skills.acrobatics.value, "message":"is being acrobatic"},
    "Animal Handling":        	{"is_tool": False, "mod":character().skills.animalHandling.value, "message":"is handling animals"},
    "Perception":             	{"is_tool": False, "mod":character().skills.perception.value, "message":"is being perceptive"},
    "Nature":                 	{"is_tool": False, "mod":character().skills.nature.value, "message":"uses natural knowledge"},
    "Sleight of Hand":        	{"is_tool": False, "mod":character().skills.sleightOfHand.value, "message":"uses their quick fingers"},
    "Survival":               	{"is_tool": False, "mod":character().skills.survival.value, "message":"is surviving"},
    "Stealth":                	{"is_tool": False, "mod":character().skills.stealth.value, "message":"is stealthing"},
    "Medicine":               	{"is_tool": False, "mod":character().skills.medicine.value, "message":"uses medicinal knowlege"},
    "Insight":                	{"is_tool": False, "mod":character().skills.insight.value, "message":"is being insightful"},
    "Religion":               	{"is_tool": False, "mod":character().skills.religion.value, "message":"is being pious"},
    "Deception":              	{"is_tool": False, "mod":character().skills.deception.value, "message":"is being deceptive"},
    "Intimidation":           	{"is_tool": False, "mod":character().skills.intimidation.value, "message":"is being intimidating"},
	"Aarakocra":  				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Bullywug":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Dwarvish":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Elvish":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Giant":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Gnomish":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Gith":    					{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Goblin":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Halfling":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Orc":    					{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Abyssal":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Celestial":    			{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Draconic":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Deep Speech":    			{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Infernal":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Primordial":    			{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Sylvan":    				{"is_tool": None, "mod":intelligenceMod, "message":None},
    "Undercommon":				{"is_tool": None, "mod":intelligenceMod, "message":None},
	"Light Armor":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Medium Armor":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Heavy Armor":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Shield":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Land Vehicles":    		{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Water Vehicles":    		{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Club":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Dagger":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Greatclub":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Handaxe":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Javelin":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Light Hammer":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Mace":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Quarterstaff":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Sickle":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Spear":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Light Crossbow":    		{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Dart":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Shortbow":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Sling":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Battleaxe":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Flail":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Glaive":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Greataxe":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Greatsword":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Halberd":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Lance":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Longsword":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Maul":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Morningstar":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Pike":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Rapier":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Scimitar":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Shortsword":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Trident":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "War Pick":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Warhammer":    			{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Whip":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Blowgun":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Hand Crossbow":    		{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Light Crossbow":    		{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Heavy Crossbow":    		{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Longbow":    				{"is_tool": None, "mod":character().skills.athletics.value, "message":None},
    "Net":    					{"is_tool": None, "mod":character().skills.athletics.value, "message":None}
}
character().set_cvar("stats", dump_json(stats))
</drac2>