<drac2>
stats = {
    "Dice Set":               {"is_tool": True, "mod":charismaMod},
    "Playing Card Set":       {"is_tool": True, "mod":charismaMod},
    "Bagpipes":               {"is_tool": True, "mod":charismaMod},
    "Drum":                   {"is_tool": True, "mod":charismaMod},
    "Dulcimer":               {"is_tool": True, "mod":charismaMod},
    "Lute":                   {"is_tool": True, "mod":charismaMod},
    "Flute":                  {"is_tool": True, "mod":charismaMod},
    "Lyre":                   {"is_tool": True, "mod":charismaMod},
    "Horn":                   {"is_tool": True, "mod":charismaMod},
    "Pan Flute":              {"is_tool": True, "mod":charismaMod},
    "Shawm":                  {"is_tool": True, "mod":charismaMod},
    "Viol":                   {"is_tool": True, "mod":charismaMod},
    "Cobbler's Tools":        {"is_tool": True, "mod":dexterityMod},
    "Disguise Kit":           {"is_tool": True, "mod":dexterityMod},
    "Glassblower's Tools":    {"is_tool": True, "mod":dexterityMod},
    "Jeweler's Tools":        {"is_tool": True, "mod":dexterityMod},
    "Potter's Tools":         {"is_tool": True, "mod":dexterityMod},
    "Tinker's Tools":         {"is_tool": True, "mod":dexterityMod},
    "Thieves' Tools":         {"is_tool": True, "mod":dexterityMod},
    "Weaver's Tools":         {"is_tool": True, "mod":dexterityMod},
    "Woodcarver's Tools":     {"is_tool": True, "mod":dexterityMod},
    "Alchemist's Supplies":   {"is_tool": True, "mod":intelligenceMod},
    "Calligrapher's Supplies":{"is_tool": True, "mod":intelligenceMod},
    "Cartographer's Tools":   {"is_tool": True, "mod":intelligenceMod},
    "Poisoner's Kit":         {"is_tool": True, "mod":intelligenceMod},
    "Carpenter's Tools":      {"is_tool": True, "mod":strengthMod},
    "Leatherworker's Tools":  {"is_tool": True, "mod":strengthMod},
    "Mason's Tools":          {"is_tool": True, "mod":strengthMod},
    "Smith's Tools":          {"is_tool": True, "mod":strengthMod},
    "Land Vehicles":          {"is_tool": True, "mod":strengthMod},
    "Water Vehicles":         {"is_tool": True, "mod":strengthMod},
    "Brewer's Supplies":      {"is_tool": True, "mod":wisdomMod},
    "Cook's Utensils":        {"is_tool": True, "mod":wisdomMod},
    "Herbalism Kit":          {"is_tool": True, "mod":wisdomMod},
    "Painter's Supplies":     {"is_tool": True, "mod":wisdomMod},
    "Navigator's Tools":      {"is_tool": True, "mod":wisdomMod},
    "Performance":            {"is_tool": False, "mod":character().skills.performance.value},
    "History":                {"is_tool": False, "mod":character().skills.history.value},
    "Persuasion":             {"is_tool": False, "mod":character().skills.persuasion.value},
    "Arcana":                 {"is_tool": False, "mod":character().skills.arcana.value},
    "Athletics":              {"is_tool": False, "mod":character().skills.athletics.value},
    "Investigation":          {"is_tool": False, "mod":character().skills.investigation.value},
    "Acrobatics":             {"is_tool": False, "mod":character().skills.acrobatics.value},
    "Animal Handling":        {"is_tool": False, "mod":character().skills.animalHandling.value},
    "Perception":             {"is_tool": False, "mod":character().skills.perception.value},
    "Nature":                 {"is_tool": False, "mod":character().skills.nature.value},
    "Sleight of Hand":        {"is_tool": False, "mod":character().skills.sleightOfHand.value},
    "Survival":               {"is_tool": False, "mod":character().skills.survival.value},
    "Stealth":                {"is_tool": False, "mod":character().skills.stealth.value},
    "Medicine":               {"is_tool": False, "mod":character().skills.medicine.value},
    "Insight":                {"is_tool": False, "mod":character().skills.insight.value},
    "Religion":               {"is_tool": False, "mod":character().skills.religion.value},
    "Deception":              {"is_tool": False, "mod":character().skills.deception.value},
    "Intimidation":           {"is_tool": False, "mod":character().skills.intimidation.value}
}
character().set_cvar("stats", dump_json(stats))
</drac2>